### ISSUE TITLE
count down TTL even if from ANAME?

### ISSUE THREAD

**Issue by Habbie** [each/draft-aname#18]
Via Jinmei:

> - Section 3.1
>
>    Address records cached locally MUST have a limited TTL.  The initial
>    TTL for locally-cached address records MUST be set to the lesser of
>    the ANAME TTL and the TTL of the address records retrieved from the
>    ANAME <target>.  The local TTL MUST count down, just as it would in a
>    conventional resolver cache.[...]
>
>   Should the local TTL count down, even if the initial value is from
>   the ANAME TTL?  I suspect that's not the intent, and if I'm correct
>   I think the current text is confusing and should clarify it.

**Comment by each** [comment]
Addressed in dfc1cc87bdb0668acae5f8dd929a147be0278252
