### ISSUE TITLE
fix diacritics

### ISSUE THREAD

**Issue by Habbie** [each/draft-aname#21]
Hakan Lindqvist and Jan Vcelak have been ASCII-fied from their original spellings. We should try to fix this, at least for the final publish as RFC.

**Comment by each** [comment]
After much trying, I haven't been able to find a way to fix this in pandoc2rfc, but we can edit diacritics by hand in draft.xml before final submission.

**Comment by Habbie** [comment]
This is the 'worst case' scenario I assumed, yes :)

**Comment by Habbie** [comment]
I understand IETF won't allow non-ASCII submissions for a long time.
