### ISSUE TITLE
note about forwarding resolvers

### ISSUE THREAD

**Issue by stbuehler** [each/draft-aname#24]
Something like:

> Forwarding resolvers not trusting their upstream to support ANAME MAY query for ANAME directly when queried for A/AAAA

**Comment by matje** [comment]
I don't think we should add special logic for ANAME processing: The ANAME is signed so it is trustworthy. Also there is no text prohibiting this so if an implementation wants to do an additional ANAME query because it is paranoid, there is nothing stopping him from doing that.
