### ISSUE TITLE
Maximum TTL

### ISSUE THREAD

**Issue by fanf2** [each/draft-aname#30]
In https://github.com/each/draft-aname/commit/5a00a98f2291d5014de2738701d913c75b7646f5 I've said that the sibling TTL is the max of the ANAME and the target records.

I think it should actually take note of the TTLs of intermediate records: CNAME processing in resolvers effectively respects the TTL of each link in the chain.

**Comment by each** [comment]
On Sun, Oct 14, 2018 at 12:12:09AM -0700, Tony Finch wrote:
> In https://github.com/each/draft-aname/commit/5a00a98f2291d5014de2738701d913c75b7646f5 I've said that the sibling TTL is the max of the ANAME and the target records.
> 
> I think it should actually take note of the TTLs of intermediate records: CNAME processing in resolvers effectively respects the TTL of each link in the chain.

Shouldn't it in fact be the *min* of all intermediate TTLs?

**Comment by fanf2** [comment]
Sigh, yes, what I wrote in the draft is the right way round, I'm clearly not quite awake yet :-)

**Comment by matje** [comment]
I think this should be the minimum of all intermediate TTLs, excluding the ANAME record itself.

**Comment by each** [comment]
Why excluding the ANAME?

**Comment by matje** [comment]
See my reasoning on the dnsop mailing list:
```
The logic is that ANAME is likely to be a more static record, while its
target address records are expected to be more dynamic. Therefor it may
make sense to set different TTLs for the different RRsets, meaning we
should not try to match the ANAME TTL and the TTL of the address records.
```

I should have been more clear perhaps: I would like to include the initializing ANAME (the one that is in the zone) when determining the final TTL, not the ANAME records that are encountered during target lookup.
