### ISSUE TITLE
ANAME precedence

### ISSUE THREAD

**Issue by matje** [each/draft-aname#58]
Should an A or AAAA record next to the ANAME should take precedence or not.

1. ANAME takes precedence, target lookup replace sibling A/AAAA records.
2. sibling address records take precedence, don't do a target lookup for an address type next to the ANAME.

When ANAME takes precedence, the logic will always update the address records, with the intent to improve the answer. When the sibling address records take precedence, it has the property that you can set up ANAME for only one address type, for example ANAME for A but not for AAAA.

Other options could be: Don't spend any words on this, don't enforce a priority order, adapt ANAME in such a way that it has the "set up for one address type" property.

**Comment by gibson042** [comment]
I strongly believe that ANAME processing should be understood as sibling override, regardless of whether the software performing it is a source-of-truth authoritative server, a downstream authoritative server, or a resolver—each hop closer to the query originator is an opportunity to provide an answer that is better for them. Letting sibling records take precedence over ANAME would be an uncomfortable inversion that muddies the water about when software that understands ANAME is permitted to leverage that understanding.

**Comment by aeden** [comment]
Our current implementation always performs the ANAME resolution even with sibling A or AAAA records. I am against sibling A/AAAA records taking precedence over ANAME in the specification.

**Comment by matje** [comment]
I only heard voices for ANAME taking precedence over A and AAAA. The draft is already in good shape for that. I have reworded the substitution process slightly in #60 and once that gets merged, this issue can be closed.
